language: java
sudo: false
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
install: true
script: ./travis/build.sh
env:
  global:
  # REPO_PASSWORD
  - secure: b/vNiqFcPkg/7pg5bZ7p68aSYAUgR1stOqCFnTRm4WnMFtiuJwEONPlnOo3GDb5ppJvrJAMpkfBpxwMyapPTPyz2PqOLHpGXWJBxaCLXMiEJCQSOL5eNsv5I20x3lC76xfTXum+nnjimWMiyDIZcMOmdq1k4FAP2loGobRuAycbWSIdXMyIqHNNFTlh6uW4Y6ubOBhl7mvkLMKmbxZOGxBJe/J66TfCihEwwz4uIHxfR/Mf146tJEy8oSTBqyCOxE4xZOa/fdJfKyzri8kcEKQNfgpcULIICfNC9LEuawL1B+hj+PTjW4/bCLgoSzwp7qr/rODvGmz9whGyPwoCtJWbOZg4LoHVkMvKDx8s3ld3E3TNsHfE2OaDdsh6YWHZE4dTw+oDHmjBQQ3Z5MNC2/sXXg8QroczUnve8clq/bNGiodj2LSZRCBGT5uKV/Q7S4hZm9owQu0geUy4zSafDOWrhti3YQK/67hnen4lnY4ESXguNecF+jqe6L5+5sxCnKhFhulXSzDskcezSkO/wHbvEZYuOm191L93jx24vRVB4QEPY6U0OW42Ku08WrxiG8VAkBa4gIye7MCs2EthU6IWxjFhsDV5EolIliKcq0l0dNhAHFFBUHgJ5dGDmhiof6fVS5ixIzNQB4V/PeeCIUs6XdYY6mhsNW1EhPPJ++lE=
  # TOMCAT_USERNAME
  - secure: ojn19kLrRjfNGEindivufyogtYVMbUHo5pyQmB5dXd3SojxEUIyYx7o7tYCfFcCQ0AmVZCEwmpU651R/m4cKobbx0suF6epozizhvS93Egc0RR5xXyUAHi0SgEUOf8fsv1V3SYy8gdaqcFFXTg5owtkdnfjjspIqrX8xZoVHItH21g06Izu1Zag+3/ovUrINY6TQM1voMQdBWlLzJ5N/gtY2AfhBGzdqa0tfSrpv23xRu1jrD0jZtE271tCHVlAFM9uJOLOP9nQYBxXC5DAoTgEVZb3yPgyiJgw0vWHneTEF5X+CQ5o7RXJQOWVdLJw5ZKfjLyFyHai44S1TA+x0WvAZjmwQvMlqD3PoTOd8dyz94eRU4lv2FE+bnzLjpBeSwLBl9tk9CketJIaQcOMUUOnuAidvgiKfDkNuMt2q5LcE0qFfjrgY8k8DBtYI13hodGMIIuUP3zXaH4nK2jOfgzVzshCpVk3pwsqtxwDjnTUIFvv8IJO5K5kC6dDlWbH+J7yrX4kPj7GKFxYcdWsjSg59E/qjeeHomqzq7PMj1XqWRgDo4JmqZxU+qgr3f2tabyP8whFdbDZTQgLuX1y0lP+7hUzOwkoi/mnqUAHlj81vRylBcX/gFtI+pJQwD7ZDwLfAmBPrkizetavxTWROnAuOoeRlzseVpclAscM2SEo=
  # TOMCAT_PASSWORD
  - secure: Hwsrlm4AblXCNdW837Z6Omsjw8sRrWA3V5/b+EtFEIzHEQE3Yd+LpKG6nW79QIKNQAwDxWb6YiDd7iFUPXYuPGW30HNvkq0VBUbWetuXF87tz9oJLwTZal8xhAk7LS9P+edf7f22UI1rdMj7nBG8VKTF9zWqm2vWphhJIMJBHIsAlk04qxOgDVPbhiccbJJ7TBpt3sIADmWeD8Z1gl23VolW+u/OELUg0Q+2JA+8RChL6vcju2/uh7pUrkMl3nqMrm8Go6EC6EDvtpOW8jcd5ov76t8opAmU6gfNWE5ZP72s9UHXuHsw+iFyO5QU3LdYMNBYRCisoYCRudy7O8uOEVsD35GaFhZmjAggawHu8FVUrnCAHYla23vEpgwxhyt0tCn9jVNJlViQMrF0S8ph7tQtykv+jpVZa+JZIyQOLDItbTxSnRqNswTEpFqZgYKbXL9DMtnt2rKeJKb48GUY8KTxM7RswczQOJ/X5nA+n2d86kPf8d4etQcXAoyfAzOv7N8JTW2lLnY/AFJpg1sHUnXKOQTNpXxHXJGrT9tHsNVHzY+IOZKqvCsfB0T5IlOslD62OgHGO5V5N9EycKyHON0nCPzFRx+0Ej+pm+leq+WQq4NYCO605qyE+WnA96L8ZiVhTTxQYeqcWxISzi+UTv9o/Mw4tcJJBz8ePmZVkAY=
notifications:
  irc: "irc.rizon.net#runelite"
